apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
spec:
  containers:
  - name: hello-world
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports: 
      - name: web
        containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: netology-svc
spec: 
  selector:
    app: netology-web
  ports:
      - protocol: TCP
        port: 80
        targetPort: web