---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.34.192
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: cent
    ansible_ssh_private_key_file: /home/Ioan/.ssh/id_ansible