---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 
  - src: git@github.com:BorisHrenNakodit/vector.git
    scm: git
    version: "1.0.0"
    name: vector-role
  - src: git@github.com:BorisHrenNakodit/ansible-clickhouse-deb.git
    scm: git
    version: "1.0.0"
    name: clickhouse_deb