apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  selector:
    app: ng
  ports:
  - name: ngi
    port: 8001
    targetPort: nginx-port
  - name: multitool
    port: 8080
    targetPort: port-mul
