apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-ngtool
  namespace: netol
spec:
  selector:
    matchLabels:
      app: ngtool
  template:
    metadata:
      labels:
        app: ngtool
    spec:
      volumes:
      - name: index-file
        configMap:
         name: ng-index
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: ng-port
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: index-file
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
          name: tool-port
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: cfg-tool
                key: port