apiVersion: v1
kind: Service
metadata:
  name: web-ngtool
  namespace: netol
spec:
  selector:
    app: ngtool
  ports:
  - name: web-ng
    protocol: TCP
    port: 9001
    targetPort: ng-port
  - name: web-tool
    protocol: TCP
    port: 9002
    targetPort: 11443
