apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testioan
  namespace: netol
subjects:
- kind: User
  name: testioan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io