apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  namespace: netol
spec:
  storageClassName: local
  resources:
    requests:
      storage: 30Mi
  accessModes:
    - ReadWriteOnce
