apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: netol
spec:
  resources:
    requests:
      storage: 30Mi
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
