---
- name: Vector
  hosts: clickhouse
  handlers:
    - name: Restart vector
      become: true
      ansible.builtin.systemd:
        name: vector
        state: started
  tasks:
    - name: Dir create
      become: true
      ansible.builtin.file:
        path: /home/deb/Vector
        state: directory
        mode: "0755"
    - name: Get Vector distrib
      become: true
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.46.1/vector_0.46.1-1_amd64.deb"
        dest: /home/deb/Vector/Vector-0.46.1.deb
        mode: "0644"
    - name: Install Vector
      become: true
      ansible.builtin.apt:
        deb: /home/deb/Vector/Vector-0.46.1.deb
    - name: template conf vector
      become: true
      ansible.builtin.template:
        src: ./vector.j2
        dest: /etc/vector/vector.yaml       
    - name: Vector config
      become: true
      ansible.builtin.replace:
        backup: true
        path: /lib/systemd/system/vector.service
        regexp: 'ExecStart=/usr/bin/vector*$'
        replace: "ExecStart=/usr/bin/vector --config /etc/vector/vector.yaml"
      notify: Restart vector
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        pkg:
          - clickhouse-client
          - clickhouse-server
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
