apiVersion: v1
kind: Service
metadata:
  name: ntd-service
spec:
  selector:
    app: nt
  ports:
  - protocol: TCP
    name: nt-nginx
    port: 80
    targetPort: 80
  - protocol: TCP
    name: nt-multitool
    port: 8080
    targetPort: 11443
