apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-front
  namespace: net
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: frontend
        image: wbitt/network-multitool
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: HTTP_PORT
            value: "11443"

---
apiVersion: v1
kind: Service
metadata:
  name: s-front
  namespace: net
spec:
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 11443
