apiVersion: v1
kind: Service
metadata:
  name: nt-svc
spec:
  selector:
    app: nt
  ports:
  - name: nginx
    port: 9001
    targetPort: port-ngx
  - name: multitool
    port: 9002
    targetPort: port-mul