apiVersion: v1
kind: Service
metadata:
  name: cu
spec:
  type: NodePort
  selector:
    app: nt
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: multitool
    protocol: TCP
    port: 11443
    nodePort: 30433